# Generated by Django 4.2.13 on 2024-07-12 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabricaNeeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandas',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fabricaNeeds.estoque'),
        ),
    ]
