# Generated by Django 4.2.13 on 2024-07-14 20:31

from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricaNeeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=20)),
                ('cliente', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Pendente', max_length=15)),
                ('data_pagamento', models.DateField(auto_now_add=True)),
                ('data_aprovacao', models.DateField(null=True)),
                ('descricao', models.CharField(max_length=100, null=True)),
                ('pix_copiacola', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
        migrations.AlterField(
            model_name='demandas',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fabricaNeeds.estoque'),
        ),
    ]
