# Generated by Django 4.2.13 on 2024-07-12 18:16

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricaNeeds', '0002_alter_demandas_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
    ]
