# Generated by Django 4.2.13 on 2024-07-14 19:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fabricaNeeds', '0003_pagamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentos',
            name='data_aprovacao',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pagamentos',
            name='data_pagamento',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagamentos',
            name='descricao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pagamentos',
            name='pix_copiacola',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pagamentos',
            name='status',
            field=models.CharField(default='Pendente', max_length=15),
        ),
    ]
