# Generated by Django 4.2.13 on 2024-08-22 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabricaNeeds', '0003_remove_demandas_nome_produto_alter_demandas_produto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RetirarEstoque',
        ),
    ]
