# Generated by Django 4.2.13 on 2024-08-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricaNeeds', '0004_delete_retirarestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandas',
            name='produto_nao_cadastrado',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
