# Generated by Django 4.2.13 on 2024-08-25 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabricaNeeds', '0005_demandas_produto_nao_cadastrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandas',
            name='produto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fabricaNeeds.estoque'),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='produto_nao_cadastrado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
