# Generated by Django 5.0.4 on 2024-05-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricaNeeds', '0020_delete_contribuicoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandas',
            name='nome_produto',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
