# Generated by Django 5.0.4 on 2024-06-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricaNeeds', '0022_alter_demandas_nome_produto_alter_demandas_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuinte',
            name='token',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contribuinte',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
