# Generated by Django 4.2.13 on 2024-07-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='github_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
