# Generated by Django 4.2.13 on 2024-07-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_github_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
