# Generated by Django 4.2.13 on 2024-07-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='verified',
        ),
        migrations.AddField(
            model_name='usuario',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
