# Generated by Django 4.2.13 on 2024-07-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
