# Generated by Django 4.2.13 on 2024-07-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_remove_usuario_verified_usuario_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='github_username',
            new_name='github_token',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='name',
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
