# Generated by Django 4.2.13 on 2024-07-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_remove_usuario_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='github_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
