# Generated by Django 4.2.13 on 2024-07-09 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_rename_github_username_usuario_github_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='github_token',
            new_name='github_id',
        ),
    ]
