# Generated by Django 4.2.13 on 2024-07-09 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_usuario_github_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='github_token',
            new_name='github_id',
        ),
    ]
