# Generated by Django 4.2.13 on 2024-07-09 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_rename_github_token_usuario_github_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='github_username',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='verified',
        ),
    ]
